os:
  - linux
  - osx

language: rust
rust:
  - stable

before_install:
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update && brew install cairo gtk+3; fi"

addons:
  apt:
    packages:
      - libgtk-3-dev
